### ISSUE TITLE
老哥能分享一下DFDC数据集吗 

### ISSUE THREAD

**Issue by AssassinXY** [Allenem/graduation-design#1]
我最近也在做该方向的，但是DFDC数据集需要亚马逊账号才能下载，不知道老哥从哪下载的，能不能提供一下。

**Comment by Allenem** [comment]
链接：https://pan.baidu.com/s/1_GgADkJpHrM6kM0AhF7nrg

提取码：o4rr

复制这段内容后打开百度网盘手机App，操作更方便哦

:warning: 上面包含三个数据集，记得每个数据集的压缩包都下载完成之后，再对该数据集任何一个压缩包解压，既可解压该数据集所有压缩包，这样数据才是完整的！！！

如果失效的话，再加我QQ联系吧！  :smile:

**Comment by yttttkskr** [comment]
您好，我看原数据集是400多G，但我下载下来的数据集大小是20多个G，我只看到6个DFD的压缩包，请问是没上传全还是说训练只用这些就行了呢

**Comment by Allenem** [comment]
> 您好，我看原数据集是400多G，但我下载下来的数据集大小是20多个G，我只看到6个DFD的压缩包，请问是没上传全还是说训练只用这些就行了呢

你用这个处理过的视频文件数据集训练即可（注意ipynb里面的数据集链接有一个过期了，但是下面这个readme文件里面的数据集链接都可以打开，你使用即可）：

https://github.com/Allenem/graduation-design/tree/master/Spectrum_SVM4Image_and_Resnet_LSTM4Video#2%E5%AE%9E%E9%AA%8C%E4%BA%8C%E6%B7%B1%E5%BA%A6%E5%AD%A6%E4%B9%A0%E5%88%86%E7%B1%BB%E5%99%A8

[FaceForensics++ Real and fake processed videos](https://drive.google.com/drive/folders/1VIIWRLs6VBXRYKODgeOU7i6votLPPxT0?usp=sharing)
[Celeb-DF Fake processed videos](https://drive.google.com/drive/folders/1SxCb_Wr7N4Wsc-uvjUl0i-6PpwYmwN65?usp=sharing)
[Celeb-DF Real processed videos](https://drive.google.com/drive/folders/1g97v9JoD3pCKA2TxHe8ZLRe4buX2siCQ?usp=sharing)
[DFDC Fake processed videos](https://drive.google.com/drive/folders/1yz3DBeFJvZ_QzWsyY7EwBNm7fx4MiOfF?usp=sharing)
[DFDC Real processed videos](https://drive.google.com/drive/folders/1wN3ZOd0WihthEeH__Lmj_ENhoXJN6U11)

**Comment by yttttkskr** [comment]
感谢
